import pandas as pd


def explore_dataset(df):
    print("\n========== DATASET EXPLORATION ==========")
    print("\nDataset Shape:")
    print(df.shape)
    print("\nFirst 5 Rows:")
    print(df.head())
    print("\nColumn Names:")
    print(df.columns.tolist())
    print("\nData Types:")
    print(df.dtypes)
    print("\nDataset Information:")
    df.info()
    print("\nStatistical Summary:")
    print(df.describe())
    print("\nMissing Values:")
    print(df.isnull().sum())
    print("\nDuplicate Rows:")
    print(df.duplicated().sum())
    print("\nUnique Values:")
    print(df.nunique())


def generate_analysis(df):
    analysis = {}

    # Requirement 1: Analyze Customer Behavior
    customer_sales = (
        df.groupby("Customer ID")["Revenue"]
        .sum()
        .sort_values(ascending=False)
    )

    analysis["Total Customers"] = df["Customer ID"].nunique()

    if len(customer_sales) > 0:
        analysis["Top Customer"] = customer_sales.index[0]
        analysis["Top Customer Spending"] = customer_sales.iloc[0]

    # Requirement 2: Product Category Analysis
    # The supplied dataset has no Category column, so no category is invented.
    if "Category" in df.columns:
        category_sales = (
            df.groupby("Category")["Revenue"]
            .sum()
            .sort_values(ascending=False)
        )
        if len(category_sales) > 0:
            analysis["Best Product Category"] = category_sales.index[0]
            analysis["Best Category Revenue"] = category_sales.iloc[0]
    else:
        analysis["Product Category Analysis"] = (
            "Not available - dataset does not contain a Category column"
        )

    # Requirement 3: Monthly Sales Trend
    monthly_sales = (
        df.groupby(["Year", "Month", "Month_Name"])["Revenue"]
        .sum()
        .reset_index()
        .sort_values(["Year", "Month"])
    )

    if len(monthly_sales) > 0:
        best_month = monthly_sales.loc[monthly_sales["Revenue"].idxmax()]
        analysis["Best Sales Month"] = best_month["Month_Name"]
        analysis["Best Month Revenue"] = best_month["Revenue"]

    # Requirement 4: Customer Lifetime Value
    # Historical CLV = total revenue generated by a customer.
    # Predictive CLV would require additional assumptions/data such as margin,
    # churn probability and expected future lifespan, which are not present.
    customer_lifetime = (
        df.groupby("Customer ID")
        .agg(
            Total_Revenue=("Revenue", "sum"),
            Total_Orders=("Invoice", "nunique"),
            First_Purchase=("InvoiceDate", "min"),
            Last_Purchase=("InvoiceDate", "max"),
        )
        .reset_index()
    )

    if len(customer_lifetime) > 0:
        customer_lifetime["Lifetime_Days"] = (
            customer_lifetime["Last_Purchase"]
            - customer_lifetime["First_Purchase"]
        ).dt.days
        customer_lifetime["Lifetime_Days"] = (
            customer_lifetime["Lifetime_Days"].fillna(0).replace(0, 1)
        )
        customer_lifetime["Average_Order_Value"] = (
            customer_lifetime["Total_Revenue"]
            / customer_lifetime["Total_Orders"].replace(0, 1)
        )
        customer_lifetime["Customer_Lifetime_Value"] = (
            customer_lifetime["Total_Revenue"]
        )
        analysis["Average Customer Lifetime Value"] = (
            customer_lifetime["Customer_Lifetime_Value"].mean()
        )

    # Requirement 5: Top Customer Analysis
    top_customer = (
        df.groupby("Customer ID")["Revenue"]
        .sum()
        .sort_values(ascending=False)
    )

    if len(top_customer) > 0:
        analysis["Top Customer"] = top_customer.index[0]
        analysis["Top Customer Revenue"] = top_customer.iloc[0]

    # Requirement 6: Revenue Analysis
    analysis["Total Orders"] = df["Invoice"].nunique()
    analysis["Total Sales"] = df["Sales"].sum()
    analysis["Total Revenue"] = df["Revenue"].sum()
    analysis["Total Quantity Sold"] = df["Quantity"].sum()
    analysis["Average Order Value"] = (
        df.groupby("Invoice")["Revenue"].sum().mean()
    )
    analysis["Highest Transaction Revenue"] = df["Revenue"].max()
    analysis["Lowest Transaction Revenue"] = df["Revenue"].min()

    # Requirement 7: Product Profitability
    # No actual cost/profit column exists in the supplied dataset.
    # Therefore, actual profitability is not fabricated; revenue performance
    # is provided instead.
    product_profitability = (
        df.groupby("StockCode")
        .agg(
            Product_Name=("Description", "first"),
            Quantity_Sold=("Quantity", "sum"),
            Revenue=("Revenue", "sum"),
            Average_Price=("Price", "mean"),
        )
        .reset_index()
    )

    product_profitability["Revenue_Per_Unit"] = (
        product_profitability["Revenue"]
        / product_profitability["Quantity_Sold"].replace(0, 1)
    )

    product_profitability = product_profitability.sort_values(
        "Revenue", ascending=False
    )

    if len(product_profitability) > 0:
        analysis["Best Product"] = product_profitability.iloc[0]["Product_Name"]
        analysis["Best Product Revenue"] = product_profitability.iloc[0]["Revenue"]

    analysis["Product Profitability"] = (
        "Actual profitability not available - dataset does not contain product cost data"
    )

    # Requirement 8: Generate Business Insights
    country_sales = (
        df.groupby("Country")["Revenue"]
        .sum()
        .sort_values(ascending=False)
    )

    if len(country_sales) > 0:
        analysis["Best Country"] = country_sales.index[0]

    if "Is_Cancelled" in df.columns:
        analysis["Cancelled Transactions"] = df["Is_Cancelled"].sum()

    return analysis


def save_business_insights(analysis, file_path):
    with open(file_path, "w", encoding="utf-8") as file:
        for key, value in analysis.items():
            if isinstance(value, float):
                value = round(value, 2)
            file.write(f"{key}: {value}\n")
